# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inserzioni', '0001_initial'),
        ('utenti', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orario_acquisto', models.DateTimeField(auto_now_add=True)),
                ('compratore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compratore', to='utenti.Profile')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inserzioni.Prodotto')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to='utenti.Profile')),
            ],
            options={
                'verbose_name': 'ordine',
                'verbose_name_plural': 'ordini',
                'ordering': ('orario_acquisto',),
            },
        ),
    ]
