# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utenti', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('orario_creazione', models.DateTimeField(auto_now_add=True)),
                ('orario_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categorie',
                'ordering': ('nome',),
                'verbose_name': 'catergoria',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilita', models.BooleanField(default=True)),
                ('venduto', models.BooleanField(default=False)),
                ('orario_creazione', models.DateTimeField(auto_now_add=True)),
                ('orario_aggiornamento', models.DateTimeField(auto_now=True)),
                ('immagine', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inserzioni.Categoria')),
            ],
            options={
                'verbose_name_plural': 'prodotti',
                'ordering': ('-orario_creazione',),
                'verbose_name': 'prodotto',
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('orario_creazione', models.DateTimeField(auto_now_add=True)),
                ('orario_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'regioni',
                'ordering': ('nome',),
                'verbose_name': 'regione',
            },
        ),
        migrations.AddField(
            model_name='prodotto',
            name='regione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inserzioni.Regione'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.Profile'),
        ),
        migrations.AlterIndexTogether(
            name='prodotto',
            index_together=set([('id', 'slug')]),
        ),
    ]
