# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaggi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to='utenti.Profile', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utenti.Profile', verbose_name='User'),
        ),
    ]
